# Generated by Django 5.2.5 on 2025-08-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
