# Generated by Django 5.2.5 on 2025-08-12 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(default=None, upload_to='movies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
