# Generated by Django 5.2.5 on 2025-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0006_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
