# Generated by Django 5.2.5 on 2025-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0007_remove_movie_video_file_movie_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(default=1, upload_to='movies/'),
            preserve_default=False,
        ),
    ]
