# Generated by Django 5.2.5 on 2025-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0008_remove_movie_video_url_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cloudinary_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
