# Generated by Django 5.2.5 on 2025-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0009_movie_cloudinary_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
