# Generated by Django 5.2.5 on 2025-08-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0010_alter_movie_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cloudinary_video_url',
        ),
    ]
