# Generated by Django 5.2.5 on 2025-09-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0012_otprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
