# Generated by Django 5.2.5 on 2025-09-03 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0014_userwatchedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwatchedmovie',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
