# Generated by Django 5.2.5 on 2025-09-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0015_alter_userwatchedmovie_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWatchedMovie',
        ),
    ]
