# Generated by Django 5.2.5 on 2025-09-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0018_userwatchedmovie_delete_continuewatching'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWatchedMovie',
        ),
    ]
