# Generated by Django 5.2.5 on 2025-09-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0020_userwatchprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchprogress',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwatchprogress',
            name='last_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwatchprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
