# Generated by Django 5.2.5 on 2025-09-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0021_userwatchprogress_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatchprogress',
            unique_together={('user', 'movie')},
        ),
    ]
