# Generated by Django 5.2.5 on 2025-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa_cinema', '0022_alter_userwatchprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
